apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grades-ingress
  namespace: grades
spec:
  ingressClassName: traefik
  rules:
    - host: creamykitchen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grades-svc
                port:
                  number: 80
